import { WireframeAsset, ExportOptions, WireframeExport } from '@/types/wireframe';

export function generateWireframeExport(asset: WireframeAsset, options: ExportOptions): WireframeExport {
  const exportData: any = {
    id: asset.id,
    name: asset.name,
    category: asset.category,
    type: asset.type,
    description: asset.description,
    geometry: asset.geometry,
    material: asset.material,
  };

  if (asset.dimensions) {
    exportData.dimensions = asset.dimensions;
  }

  if (options.includeParts && asset.parts) {
    exportData.parts = asset.parts;
  }

  if (options.includeAccessories && asset.accessories) {
    exportData.accessories = asset.accessories;
  }

  if (options.includeRenderSettings && asset.renderSettings) {
    exportData.renderSettings = asset.renderSettings;
  }

  let content: string;
  let filename: string;
  let mimeType: string;

  switch (options.format) {
    case 'json':
      content = JSON.stringify(exportData, null, options.prettyPrint ? 2 : 0);
      filename = `${asset.id}.json`;
      mimeType = 'application/json';
      break;

    case 'js':
      content = `// ${asset.name}\n`;
      content += `export const ${asset.id.replace(/[^a-zA-Z0-9]/g, '_')} = `;
      content += JSON.stringify(exportData, null, options.prettyPrint ? 2 : 0);
      content += ';\n';
      filename = `${asset.id}.js`;
      mimeType = 'application/javascript';
      break;

    case 'threejs':
      const threeJSData = convertToThreeJS(exportData);
      content = JSON.stringify(threeJSData, null, options.prettyPrint ? 2 : 0);
      filename = `${asset.id}-threejs.json`;
      mimeType = 'application/json';
      break;

    case 'obj':
      content = convertToOBJ(exportData);
      filename = `${asset.id}.obj`;
      mimeType = 'text/plain';
      break;

    case 'gcode':
      content = convertToGCode(exportData);
      filename = `${asset.id}.gcode`;
      mimeType = 'text/plain';
      break;

    default:
      throw new Error(`Unsupported export format: ${options.format}`);
  }

  return { content, filename, mimeType };
}

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function convertToThreeJS(data: any): any {
  // Convert wireframe data to Three.js compatible format
  return {
    metadata: {
      formatVersion: 4.5,
      generatedBy: 'Floorplan 3D Wireframe Exporter',
      date: new Date().toISOString()
    },
    geometries: {
      [data.id]: {
        type: 'BoxGeometry',
        width: data.dimensions?.width || 100,
        height: data.dimensions?.height || 100,
        depth: data.dimensions?.depth || 100
      }
    },
    materials: {
      [`${data.id}_material`]: {
        type: 'MeshBasicMaterial',
        color: data.renderSettings?.color || 0x888888,
        wireframe: data.renderSettings?.showWireframe !== false,
        opacity: data.renderSettings?.opacity || 0.8,
        transparent: true
      }
    },
    object: {
      type: 'Mesh',
      geometry: data.id,
      material: `${data.id}_material`,
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1]
    }
  };
}

function convertToOBJ(data: any): string {
  // Basic OBJ format conversion
  let obj = `# ${data.name}\n`;
  obj += `# Generated by Floorplan 3D Wireframe Exporter\n`;
  obj += `# Date: ${new Date().toISOString()}\n\n`;

  if (data.dimensions) {
    const { width, height, depth } = data.dimensions;
    const w = width / 1000; // Convert mm to meters
    const h = height / 1000;
    const d = depth / 1000;

    // Define vertices
    obj += `v 0 0 0\n`;
    obj += `v ${w} 0 0\n`;
    obj += `v ${w} ${h} 0\n`;
    obj += `v 0 ${h} 0\n`;
    obj += `v 0 0 ${d}\n`;
    obj += `v ${w} 0 ${d}\n`;
    obj += `v ${w} ${h} ${d}\n`;
    obj += `v 0 ${h} ${d}\n`;

    // Define faces (wireframe edges)
    obj += `l 1 2 3 4 1\n`;
    obj += `l 5 6 7 8 5\n`;
    obj += `l 1 5\n`;
    obj += `l 2 6\n`;
    obj += `l 3 7\n`;
    obj += `l 4 8\n`;
  }

  return obj;
}

function convertToGCode(data: any): string {
  // Basic G-code conversion for CNC operations
  let gcode = `; ${data.name}\n`;
  gcode += `; Generated by Floorplan 3D Wireframe Exporter\n`;
  gcode += `; Date: ${new Date().toISOString()}\n\n`;
  
  gcode += 'G21 ; Set units to millimeters\n';
  gcode += 'G90 ; Absolute positioning\n';
  gcode += 'G92 ; Set position as origin\n\n';

  if (data.dimensions) {
    const { width, height, depth } = data.dimensions;
    
    gcode += '; Wireframe outline\n';
    gcode += 'G00 Z5 ; Lift tool\n';
    gcode += 'G00 X0 Y0 ; Move to start\n';
    gcode += 'G01 Z0 ; Lower tool\n';
    gcode += `G01 X${width} ; Draw width\n`;
    gcode += `G01 Y${height} ; Draw height\n`;
    gcode += `G01 X0 ; Draw back\n`;
    gcode += `G01 Y0 ; Return to start\n`;
    gcode += 'G00 Z5 ; Lift tool\n';
  }

  gcode += '\nM30 ; End program';
  return gcode;
}
